name: oauth2
version: 2.1.1
description: >-
  A client library for authenticating with a remote service via OAuth2 on
  behalf of a user, and making authorized HTTP requests with the user's
  OAuth2 credentials.
  Uses Cancelable Token HTTP Client library which allows canceling requests.
  (fully compatible with HTTP Client library)
repository: https://github.com/dart-lang/oauth2
  
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cancellation_token_http: ^1.2.0
  collection: ^1.17.1
  crypto: ^3.0.2
  http_parser: ^4.0.2

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
