name: oauth2
version: 2.1.2
description: >-
  A client library for authenticating with a remote service via OAuth2 on
  behalf of a user, and making authorized HTTP requests with the user's
  OAuth2 credentials.
  Uses Cancelable Token HTTP Client library which allows canceling requests.
  (fully compatible with HTTP Client library)
repository: https://github.com/anycode/oauth2
publish_to: https://pub.anycode.dev

environment:
  sdk: ^3.0.0

dependencies:
  cancellation_token_http: ^2.0.0
  collection: ^1.18.0
  crypto: ^3.0.3
  http_parser: ^4.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
